Feature: Initial Rough App (#2)

diff --git a/sigot b/sigot
--- a/sigot
+++ b/sigot
@@ -12,17 +12,21 @@ print_usage() {
     echo "    $0 <command> [args]"
     echo " "
     echo "Commands:"
-    echo "    help                                              Show this help message"
-    echo "    init <command> [arguments]                        Initialize a project component"
-    echo "          secrets|s [--empty]                         Generate the secrets.properties file, pass --empty to use 'empty' for all secrets"
-    echo "          ktlint|k [arguments]                        Install ktlint and integrate it with the project"
-    echo "          hooks|h [--output]                          Install the git hooks, pass --output to display the contents of the hooks"
-    echo "    gradle <command>                                  Run any gradle command"
-    echo "    add <component>                                   Add a lumo ui component"
-    echo "    clean                                             Cleans all the build files"
-    echo "    lint --all | --staged [args]                      Lint the codebase using ktlint"
-    echo "    fix [--all] [--staged]                            Fixes only staged files if --all is not passed"
-    echo "    commit|c [options]                                Stage changes, run fix, and commit"
+    echo "    help                           Show this help message"
+    echo "    init [command] [arguments]     Initialize a project component"
+    echo "          secrets|s [--empty]      Generate the secrets.properties file, pass --empty to use 'empty' for all secrets"
+    echo "          ktlint|k [arguments]     Install ktlint and integrate it with the project"
+    echo "          hooks|h [--output]       Install the git hooks, pass --output to display the contents of the hooks"
+    echo "          api:worker               Install required dependencies for the api worker"
+    echo "    gradle <command>               Run any gradle command"
+    echo "    add <component>                Add a lumo ui component"
+    echo "    clean                          Cleans all the build files"
+    echo "    lint --all | --staged [args]   Lint the codebase using ktlint"
+    echo "    fix [--all] [--staged]         Fixes only staged files if --all is not passed"
+    echo "    commit|c [options]             Stage changes, run fix, and commit"
+    echo "    cli [args]                     Run the CLI version of SIGOT"
+    echo "    api                            Commands for the API"
+    echo "    api:worker <command>           Run command helpers for the api worker"
 }
 
 check_directory() {
@@ -50,9 +54,15 @@ help)
 init)
     shift
     if [ "$#" -eq 0 ]; then
-        echo "Please specify an init command: node, path, ktlint, hooks, or secrets"
-        echo "Run 'beans help' for more information"
-        exit 1
+        "$ROOT"/scripts/init.sh
+        # Return the exit code of the init.sh
+        if [ $? -eq 0 ]; then
+            echo "✅ Project initialized successfully"
+            exit 0
+        else
+            echo "❌ Project initialization failed"
+            exit 1
+        fi
     fi
     subcommand=$1
     shift
@@ -66,6 +76,9 @@ init)
         ;;
     secrets | secret | s)
         "$ROOT"/scripts/init-secrets.sh "$@"
+        ;;
+    api:worker)
+        "$ROOT"/scripts/api-worker.sh init
         ;;
     *)
         echo "The command '$subcommand' is not a valid 'init' command. Use 'ktlint', 'secrets', or 'hooks'."
@@ -82,14 +95,14 @@ gradle | g)
     "$ROOT"/gradlew "$@"
     ;;
 add)
-  shift
-  # Check if there is a component name:
-  if [ "$#" -eq 0 ]; then
-    echo "Error: No component name provided"
-    exit 1
-  fi
-  "$ROOT"/gradlew lumo --no-configuration-cache --add "$@"
-  ;;
+    shift
+    # Check if there is a component name:
+    if [ "$#" -eq 0 ]; then
+        echo "Error: No component name provided"
+        exit 1
+    fi
+    "$ROOT"/gradlew lumo --no-configuration-cache --add "$@"
+    ;;
 clean)
     "$ROOT"/scripts/cleanup
     ;;
@@ -141,11 +154,23 @@ commit | c)
     ;;
 xcode)
     echo "Opening Xcode workspace"
-    open "$ROOT/ios/iosApp.xcworkspace"
+    open "$ROOT/apps/ios/iosApp.xcworkspace"
     ;;
 generate-image-sizes)
     shift
     node "$ROOT"/scripts/image-resource.js "$@"
+    ;;
+cli)
+    shift
+    "$ROOT"/scripts/cli.sh "$@"
+    ;;
+api)
+    shift
+    "$ROOT"/scripts/api.sh "$@"
+    ;;
+api:worker)
+    shift
+    "$ROOT"/scripts/api-worker.sh "$@"
     ;;
 *)
     echo "Unknown command: $1"
